version: '2'

services:
  proxy:
    container_name: stepik-adaptive-rating-proxy
    build: ./proxy
    ports:
      - "80:9000"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql
    container_name: stepik-adaptive-rating-mysql
    restart: always
    command: --init-file /var/lib/mysql-files/db_schema.sql
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./db/mysql:/var/lib/mysql"
      - "./db/data:/var/lib/mysql-files"
